import './globals.css';
import Navbar from './components/Navbar';
import Footer from './components/Footer/Footer';
import ClientProvider from './components/ClientProvider';

export const metadata = {
  title: 'MedSearch',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>
          <Navbar />
          {children}
          <Footer />
        </ClientProvider>
      </body>
    </html>
  );
}
